import{a as g,i as h,S as v}from"./assets/vendor-6TKiDHm1.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();g.defaults.baseURL="https://pixabay.com";const p=function(e,s){const i="/api/",l={params:{q:e,key:"10567451-e89d654aa7ed9140fe488f539",image_type:"photo",per_page:15,page:s,orientation:"horizontal",safesearch:!0}};return new Promise((t,r)=>{setTimeout(()=>{g.get(i,l).then(a=>t(a)).catch(a=>r(a))},3e3)})},y=e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <div class="gallery-card">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </div>
    </a>
  `,w=(e,s,i)=>{s.innerHTML=e,i.refresh()},m=e=>{h.error({title:"Error",message:e})},f=e=>{h.warning({title:"No results",message:e})};let L=new v(".js-gallery a");const b=document.querySelector(".js-search-form"),d=document.querySelector(".js-gallery"),o=document.querySelector(".js-loader"),n=document.querySelector(".js-load-more-btn");let u="",c=1;const S=async e=>{try{if(e.preventDefault(),u=e.currentTarget.elements.user_query.value.trim(),c=1,o.classList.add("is-hidden"),n.classList.add("is-hidden"),!u){m("Please enter a search query."),d.innerHTML="",o.classList.add("is-hidden"),n.classList.add("is-hidden");return}o.classList.remove("is-hidden");const s=await p(u,c);if(s.data.total===0)d.innerHTML="",o.classList.add("is-hidden"),f("Sorry, there are no images matching your search query. Please try again!");else{const i=s.data.hits.map(y).join("");w(i,d,L),n.classList.remove("is-hidden")}}catch(s){m(`Something went wrong: ${s.message}`)}finally{o.classList.add("is-hidden")}},E=async()=>{try{c+=1,o.classList.remove("is-hidden"),n.classList.add("is-hidden");const e=await p(u,c),s=e.data.hits.map(y).join("");d.insertAdjacentHTML("beforeend",s),L.refresh();const i=c*15;e.data.totalHits<=i?(n.classList.add("is-hidden"),f("We're sorry, but you've reached the end of search results.")):n.classList.remove("is-hidden");const{height:l}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"})}catch(e){m(`Something went wrong: ${e.message}`)}finally{o.classList.add("is-hidden")}};b.addEventListener("submit",S);n.addEventListener("click",E);
//# sourceMappingURL=commonHelpers.js.map
