import{a as y,i as p,S}from"./assets/vendor-B_3rE_6a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&i(h)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();y.defaults.baseURL="https://pixabay.com";const f=async(e,t)=>{const o="/api/",i={params:{q:e,key:"10567451-e89d654aa7ed9140fe488f539",image_type:"photo",per_page:15,orientation:"horizontal",safesearch:!0,page:t}};return y.get(o,i)},L=e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <div class="gallery-card">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </div>
    </a>
  `,v=(e,t,o)=>{t.insertAdjacentHTML("beforeend",e),o.refresh()},b=e=>{p.error({title:"Error",message:e})},c=e=>{p.warning({title:"No results",message:e})},E=document.querySelector(".js-search-form"),d=document.querySelector(".js-gallery"),l=document.querySelector(".js-loader"),a=document.querySelector(".js-load-more-btn");let w=new S(".js-gallery a"),u=1,m="",g=0,n=0;const $=async e=>{e.preventDefault(),m=e.target.elements.user_query.value.trim(),u=1,n=0,d.innerHTML="",a.classList.add("is-hidden");try{l.classList.remove("is-hidden");const{data:{hits:t,totalHits:o}}=await f(m,u);if(g=o,t.length===0)c("Sorry, there are no images matching your search query. Please try again!"),a.classList.add("is-hidden");else{n+=t.length;const i=t.map(L).join("");v(i,d,w),n<g&&a.classList.remove("is-hidden")}}catch(t){b(`Something went wrong: ${t.message}`)}finally{l.classList.add("is-hidden")}},j=async e=>{try{if(u++,l.classList.remove("is-hidden"),n>=g){c("We're sorry, but you've reached the end of search results."),a.classList.add("is-hidden"),l.classList.add("is-hidden");return}const{data:{hits:t}}=await f(m,u);if(t.length===0)c("We're sorry, but you've reached the end of search results."),a.classList.add("is-hidden");else{n+=t.length;const o=t.map(L).join("");v(o,d,w),n>=g&&(a.classList.add("is-hidden"),c("We're sorry, but you've reached the end of search results."));const{height:i}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch(t){b(`Something went wrong: ${t.message}`)}finally{l.classList.add("is-hidden")}};E.addEventListener("submit",$);a.addEventListener("click",j);
//# sourceMappingURL=commonHelpers.js.map
