import{a as g,i as h,S as w}from"./assets/vendor-6TKiDHm1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();g.defaults.baseURL="https://pixabay.com";const y=function(e,r){const a="/api/",o={params:{q:e,key:"10567451-e89d654aa7ed9140fe488f539",image_type:"photo",per_page:15,page:r,orientation:"horizontal",safesearch:!0}};return g.get(a,o)},p=e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <div class="gallery-card">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </div>
    </a>
  `,v=(e,r,a)=>{r.innerHTML=e,a.refresh()},u=e=>{h.error({title:"Error",message:e})},f=e=>{h.warning({title:"No results",message:e})};let L=new w(".js-gallery a");const b=document.querySelector(".js-search-form"),n=document.querySelector(".js-gallery"),i=document.querySelector(".js-loader"),l=document.querySelector(".js-load-more-btn");let m="",c=1;const S=async e=>{try{if(e.preventDefault(),m=e.currentTarget.elements.user_query.value.trim(),c=1,i.classList.add("is-hidden"),l.classList.add("is-hidden"),!m){u("Please enter a search query."),n.innerHTML="",i.classList.add("is-hidden"),l.classList.add("is-hidden");return}i.classList.remove("is-hidden");const r=await y(m,c);if(r.data.total===0)n.innerHTML="",i.classList.add("is-hidden"),f("Sorry, there are no images matching your search query. Please try again!");else{const a=r.data.hits.map(p).join("");v(a,n,L);const o=Array.from(n.querySelectorAll(".gallery-card img"));await Promise.all(o.map(t=>new Promise(s=>{t.onload=t.onerror=s}))),l.classList.remove("is-hidden")}}catch(r){u(`Something went wrong: ${r.message}`)}finally{i.classList.add("is-hidden")}},q=async()=>{try{c+=1,i.classList.remove("is-hidden"),l.classList.add("is-hidden");const e=await y(m,c),r=e.data.hits.map(p).join("");n.insertAdjacentHTML("beforeend",r);const a=Array.from(n.querySelectorAll(".gallery-card img")).slice(-e.data.hits.length);await Promise.all(a.map(s=>new Promise(d=>{s.onload=s.onerror=d}))),L.refresh();const o=c*15;e.data.totalHits<=o?(l.classList.add("is-hidden"),f("We're sorry, but you've reached the end of search results.")):l.classList.remove("is-hidden");const{height:t}=n.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch(e){u(`Something went wrong: ${e.message}`)}finally{i.classList.add("is-hidden")}};b.addEventListener("submit",S);l.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
